label ca1:
    stop music fadeout 1.0
    scene bg train_station
    with dissolve_scene_full
    play music t2
    "So here I am, waiting…"
    "Waiting…"
    "Waiting…"
    "The horizon looks nice - but I’m still unphased, with me being a couch potato and all."
    "That’s probably why I believe fate decided to take a dump in my sister’s mouth and have her sending me somewhere for the rest of the summer break."
    "And that means also means I have no manga or anime to watch until summer school is over."
    "Oh well… this is gonna be {i}fun…{/i}"
    "The train stops, marking the end of my journey and my window-gazing. Well... at the very least for now."
    "Nonetheless, I stand up carrying my things and walk outside of the train onto the station platform."
    "And so, the suffering begins."
    return

label ca2:
    scene bg plaza_day
    with wipeleft
    "After leaving the station, I sit down on a nearby bench before proceeding to call a number my sister handed to me before I left. She’ll take me to where I need to go, she said."
    "I sigh and call the number."
    mc "Hello?"
    "I didn’t expect she’d answer over my greeting."
    $ sm_name = "???"
    sm "Hello? Who is this?"
    mc "Uhm… It’s me, [player]... my sister told me you knew each other… and{nw}"
    $ _history_list[-1].what = "Uhm… It’s me, [player]... my sister told me you knew each other… and—"
    "She gasps and squeals in the phone."
    sm "Oh my god, really?! You’re here?! Give me a second, I’ll be there in a jiffy!"
    mc "I’m just at the{nw}"
    $ _history_list[-1].what = "I’m just at the—"
    "And she drops the call."
    "Perfectly timed, as all things should…"
    "Does she already know where I am…? Only God knows, so I just continue sitting on the bench and carry on playing a visual novel I forgot to finish eons ago."
    scene bg plaza_day
    with dissolve_scene_full
    pause 3.0
    "It’s been like… three hours…"
    "And she’s not here…"
    "Temptation almost gets the better of me as I contemplate whether to drop her another call..."
    "But that {i}would{/i} be me doubting her abilities of finding the likes of me in a \"crowd.\""
    "Or maybe it’s a little nice practice for hide and seek later?"
    "Then I spot her in the distance, panting and catching her breath just a few meters away from the bench."
    "Because I’m a smug jerk, I didn’t call her over conventionally. I gave her a phone call instead."
    "I dial."
    show sayonika 1x zorder 3 at t11
    sm "Hey… I made it… *pant* where… are…. you…?"
    "Did she really run all the way from her home just to meet me here? I’m amazed."
    "Right behind you, m’lady~"
    "As she turns around, I quickly pose in a gentlemanly manner."
    "And I dramatically drop the phone call like what those smug protagonists do in anime."
    sm 1o "Right… I’m Sayonika… you must be—"
    mc "I’m the one who gave you a call earlier."
    $ sm_name = "Sayonika"
    sm 2b "Ah! [player], right?"
    mc "Yes, that’s absolutely right."
    "Why am I acting like a British gentleman all of a sudden? Oh well, I should probably keep this guise for now, I guess." 
    "I mean, after all, I’m stuck here for about three or four months, so let’s make a good first impression to the cute girl."
    sm 1q "Well… You do act and sound classy, I’ll give you that."
    sm 3b "Anyways, you must be what your sister told me about!"
    mc "About what, hm?"
    sm "We’re gonna be roommates and classmates in summer class!"
    "If I was drinking tea and eating crumpets, I’d have spit everything out of my mouth already."
    "I was {i}not{/i} informed that I’d be tagging along to this girl’s summer classes!"
    "Hell… as her ROOMMATE as well? Ain’t fate a real jerk."
    "Nevertheless, if my whole summer’s gonna be spent with such a cute girl, I think that can all change."
    mc "It’ll be fun… I suppose..."
    sm 1w "Aw… why so sad all of a sudden? Am I not that likeable?"
    "N-no…! it’s not that…!"
    "Oh boy… I’m pretty sure I just offended a girl… time to pray to Hirohiko Araki hoping I won’t butcher my words with the filth of a thousand dumpyards."
    mc "I’m just not used being with a girl, let alone a whole season..."
    "She pulls out a smirk and winks."
    sm 3a "Ahaha~! Let’s make your summer more interesting, then!"
    mc "At least take me out to dinner first."
    sm 1b "Alright, you look famished already per se, let’s go grab a bite!"
    mc"Are you paying…?"
    "She fidgets a little while looking away from me."
    sm 2i "Ehehe…"
    mc "I’ll take that as a no."
    "I wonder how in the world she was able to get here without bringing any money at all." 
    "But I let that slip on my mind and let her lead me to a bakery." 
    "I’m just hoping she doesn’t mistake me for a walking wallet."
    return

label ca3:
    # TODO: Replace this with bakery background
    scene bg residential_day
    with wipeleft
    "We’ve made it to the bakery pretty quickly." 
    "Then again, Sayonika was profusely sweating and panting just to get here with me." 
    "I open the door for her as she enters sheepishly licking her lips." 
    "As she enters, myself included, I hear the baker shout towards her."
    
    $ n_name = "Baker"
    n "Jeez, Sayonika! Have you been running a marathon again? You're way too hyperactive even when the Angel {i}isn’t{/i} around!"
    show natsuki 1 at t11
    "I perk my head up and notice Natsuki in a baker’s outfit behind the counter." 
    "Her outfit was much different to the other bakers."
    mc "Natsuki?" 
    $ n_name = "Natsuki"
    n "Eh?"
    n "[player]! I didn’t think you'd be in this part of town! What are you here for, anyway?"
    sm "I… *pant* brought him… here…"
    mc "I didn’t know you worked for a bakery!"
    n "My bakery, mind you! Sayonika, if you’re going to bring Sherlock here, at least tell me first! Hmph!"
    mc "What’s that supposed to mean?"
    n "Don’t you know what it means? A-and why does it concern {i}you?!{/i}"
    "She intently stares down at the dough she had been kneading for a while." 
    "She then continues kneading it before putting it in the oven."
    mc "So, how long have you had this bakery for?"
    n "A while. A good friend helped me get this place going."
    sm "Why’re you so wary of mentioning her name, Suki?"
    n "Don’t call me that you baka! Look, just don’t push it; he got pretty weirded out from the last visit. I’m sure he’s fine {i}not{/i} seeing her after like, a year…"
    mc "I-it’s fine, Natsuki…"
    n "Well, what do you want, dummy?"
    mc "I, uh… well… ummm..."
    "I... don’t really know what I want right now."
    sm "Just give him some time, Natsuki…"
    n "Screw it. I’ll make something special for you! Consider it compensation for dealing with… you know who."
    # [Sink Sayonika with Pout Expression]
    sm "Heey! That’s mean…"
    n "I feel almost sorry for you, [player]. She’s a bit of a handful to deal with. I’m surprised you two hadn’t really interacted with each other during the spring break..."
    mc "Natsuki, I literally just met her properly this morning. I might’ve seen her back there, but she must’ve been more interested in Monika than me…"

    "Suddenly, Mio steps out from the side of the bakery."
    $ mi_name = "???"
    mi "What in the world is going on here?"
    n "Get back to your darn danishes, toots!"
    mi "There will never be a day… oh! Hi, [player]!"
    mc "Oh, dear God…"
    "Ah, yes. Mio..." 
    "She was the club’s newest member back in the winter and we often read Japanese classics with each other."
    "At one point, we were reading {i}The Illusion of Living{/i} with Yuri."
    "Before the spring break, she was a unique individual: cute, proper, charming…"
    "Completely out of my league at that time."
    "Things got a little out of hand during spring break when we went on a trip to an animation studio."
    "Okay, {i}maybe{/i} that was a bit of an understatement."
    "Her personality drastically changed from a proper lady to a downright ruthless monster."
    "I don’t know exactly why or how, but I’m pretty sure Monika or her boss knows."
    "I think Monika said something about it being too difficult for me to understand…?"
    "Her boss was certainly less than enthusiastic about it, and things went down."
    "I try to keep my distance, but she always seems to disregard it."
    "{i}Somebody please tell me that she isn’t obsessing over me like Yuri...{/i}"
    $ mi_name = "Mio"
    mi "What? Are you going to sta{nw}"
    $ _history_list[-1].what = "What? Are you going to stare—"
    n "I said {i}get back to your danishes!{/i} I don’t want you giving my customer here a heart attack."
    mi "As you wish, Missus Drew…"
    "Mio slips back to the side."
    n "She’s still shaken up from the break, you know?"
    mc "I’m surprised she’s working for you. Especially you!"
    sm "Yeah, me too. She’s been practically barred from you know who’s presence."
    n "Right. It’s both a rehab program and eternal torture for her. Whatever, works for me!"
    n "Say, [player]… it’ll take a few minutes for this to finish. You’re not in a rush, are you?"
    mc "Yeah, yeah! Totally fine by me, I’m in no rush."
    sm "I’m with him, so…"
    n "Well, duh! He doesn’t have a clue about this bakery, anyways. What do you want?"
    sm "Just a donut will do…"
    n "Jeez, a donut? Might as well order a coffee, too. Toots!"
    "She signals towards Mio."
    mi "Ugh, really?"
    n "Get a pot brewing, please…"
    mi "Whatever."
    "Mio walks over to the counter and turns on the coffee machine." 
    "Meanwhile, another baker walks towards Natsuki with a phone in his hand while covering it up."

    b  "Ma’am, we got a big order comin’."
    n "Ha! Of course… well, my hands are a bit tied up at the moment. Soldier! Are you ready to make history?!"
    b  "W-what do you mean?!"
    n "I want you to lead the team and handle the order while I take care of this very important order! がんばって!"
    b  "Yes, ma’am!"

    "The baker signals the rest of the team, gradually informing them of the order at hand."
    n "He’s new here, so I’m training him myself. Pretty good chap if I must say so myself…"
    mc "Ah."
    sm "She’s pretty good at training these guys."
    n "So, what brings you to this part of town, hmm?"
    mc "Well, I somehow managed to land in… summer school??"
    "Natsuki breaks out in laughter as Sayonika smirks."
    n "And what? Sayonika’s bunking with you or something?"
    # [Ehehe sprite with Sink]
    sm "Y-yeah…"
    "Natsuki continues, laughing harder."
    mc "What’s so funny, Natsuki?"
    n "It’s not what you think it is, [player]! I’ll tell you this much, it’s not dealing with school. We’re done with school, my friendo!"
    mc "Yeah, I kinda {i}was{/i} wondering how I managed to get into summer school."
    n "Because it’s not, you big dummy. It’s an organized event by Monika. She must have taken a lesson or two from Sayonika’s ol’ you know who."
    "Natsuki giggles shamelessly."
    sm "Uwaa?"
    n "My God, Sayonika… you know, I thought you were supposed to be the smart one."
    n "Did you seriously think that you, a senior, would have to go back to summer school? After you graduated and everything?"
    n "How did you out of all people not figure this out? Hell, I’m not one to read things other than manga, but I still saw it! I can totally see [player] having not realised ‘cus he’s fit yet stupid, but I didn’t know you were so… gullible."
    sm "B-but…"
    mc "Are you trying to say I’m a stereotypical jock? Well whatever, that clears things up nicely anyway, doesn’t it?"
    sm "It’s not fair! How was I supposed to know?!"
    n "It is if you look at the fine print, Sayonie! The darn thing was in quotation marks!"
    "As Natsuki pulls something out of the oven, she cackles like a witch from something out of a movie. A couple of other bakers join her in the cacklefest. Kinda freaky."
    n "Don’t stress it, [Player]." 
    n "If it’s anything I’ve learned about this chica filet over here, she may have Monika’s brains, but it doesn’t ever pull through in the mornings." 
    n "It’s almost like she goes braindead or something while she’s sleeping, and all of a sudden recovers midday! Reminds me a lot of Sayori, too…"
    mc "Well, isn’t Monika a little devil darling…"
    n "Damnnn! I can’t believe you’d actually call her that!"
    "As Natsuki finishes the pastry with chocolate filling, Mio struts over sassily with the coffee in hand."
    mi "Here, bossy boots…"
    n "Hello? There’s clearly two people here and only one cup!"
    mi "Ugh, {i}so{w=0.5}-rry{/i}."
    "Mio waltzes over sloppily to the coffee machine again and makes another cup." 
    "She returns to the counter again, cup in hand."
    mi "We good now, boss?"
    n "Perfect. Now continue your danishes."
    mi "Well, just let me know if you{nw}"
    $ _history_list[-1].what = "Well, just let me know if you—"
    n "{b}You speak when spoken to, toots!{/b}"
    "A baker nearby chuckles before replying."
    b2 "Got it, JonTron!"
    n "Finally! Someone who understands my intellectuals-only humor."
    "She smiles intently as she looked at the both of us."
    mc "So, how much will I be paying?"
    n "Isn’t she paying?"
    sm "Ummm… yeah… ehehe..."
    n "I figured. [player], don’t sweat it. It’s on the house~"
    mc "Natsuki, you don’t have to…"
    n "It’s fine! I’ll be seeing your smug face anyway after this round-the-clock busy shift."
    sm "Wait, heey! What does that mean?"
    n "Well, I’m a part of this event too, you know. Someone needs to take charge of the food!"
    mc "Well, it makes sense. The only other person who could make food is Monika, but I’m not exactly too keen on her skills… mucho gracias Natsuki."
    n "No problem. You better get a move on, I got a big order going out the counter, so… you may want to move before donuts start flying and all an’ all that jazz!"
    mc "Alright. See you soon!"

    "As we head out the door, Sayonika starts to babble."
    sm "That’s so weird. She seems so playful today."
    mc "Well, I guess running that bakery makes her happy, you know?"
    sm "I guess… well, there’s one stop I want to make first. See a good librarian."
    mc "Oh?"
    sm "I have a funny feeling she’ll be joining us in \"summer school,\" too…"
    mc "Okay…"
    sm "She runs a library that’s on the {i}cutting edge{/i} of technology."
    mc "Wha?! I can’t believe you just…! You can’t be serious!"
    "Suddenly, I remember the good times I’ve had with her." 
    "She was always calm, even when things got a bit intense." 
    "Luckily for us, she and Natsuki got along well after the spring break!" 
    "Monika keeps tabs on her so that we don’t worry about her… eccentric hobbies."
    mc "Bad pun! Bad pun! No encore!"
    sm "Ehehe~ she’s quite a gal!"
    mc "Don’t give me a heart attack, honestly… I thought she was being monitored to prevent this kind of stuff."
    sm "Come on, you have to admit that was a good pun!"
    "Reluctantly, I follow Sayonika to the public library." 
    "I don’t really know Sayonika well, despite the fact that we bumped into each other without thinking twice during spring break." 
    "However, Natsuki seems to be pretty comfortable with her." 
    "{i}Well, this will be a very, very interesting summer…{i}"
    return